version: "3.8"

services:
  app:
    image: python:3.11-slim
    volumes:
      - ./:/code
    working_dir: /code
    tty: true
    env_file:
      - .env
    entrypoint: >
      sh -c "pip install -r requirements.txt && 
             python src/main.py"
