version: "3.4"

services:
  worker:
    depends_on:
      - redis
    container_name: "pollution-connector"
    build:
      context: .
      dockerfile: infrastructure/docker/Dockerfile
    restart: unless-stopped
    command: celery -A pollution_connector.celery_configuration.celery_app worker --loglevel=INFO
    env_file:
      - .env
    networks:
      - pollution

  scheduler:
    depends_on:
      - worker
    container_name: "pollution-connector-scheduler"
    build:
      context: .
      dockerfile: infrastructure/docker/Dockerfile
    restart: unless-stopped
    command: celery -A pollution_connector.celery_configuration.celery_app beat --loglevel=INFO
    env_file:
      - .env
    volumes:
       - pollution-connector-scheduler:/scheduler/
    networks:
       - pollution

  redis:
    image: redis:6.2
    container_name: "pollution-connector-redis"
    hostname: pollution-connector-redis
    restart: unless-stopped
    networks:
      - pollution
    volumes:
      - pollution-connector-redis:/data


networks:
  pollution:
    # external: true

volumes:
  pollution-connector-scheduler:
    # external: true
  pollution-connector-redis:
    # external: true