# SPDX-FileCopyrightText: NOI Techpark <digital@noi.bz.it>
#
# SPDX-License-Identifier: CC0-1.0

version: "3.4"

services:
  importer:
    build:
      context: .
      dockerfile: infrastructure/docker/Dockerfile
      args:
        PGPASSWORD: ${DB_PWD}
    env_file:
      - .env
