# SPDX-FileCopyrightText: NOI Techpark <digital@noi.bz.it>
#
# SPDX-License-Identifier: CC0-1.0

version: "3.4"

services:
  importer:
    build:
      context: .
      dockerfile: infrastructure/docker/Dockerfile
      args:
        PGPASSWORD: ${DB_PWD}
    env_file:
      - .env
    volumes:
      - ./links:/links
    command: |
        shp2pgsql -s 4326 links/LinkStationsGeometries.shp elaboration.bluetoothlinks_tmp | psql -h prod-pg-bdp.co90ybcr8iim.eu-west-1.rds.amazonaws.com -U bdp bdp
        psql -h prod-pg-bdp.co90ybcr8iim.eu-west-1.rds.amazonaws.com -U bdp -d bdp -c "set search_path=public,intimev2,elaboration;update edge as e set linegeometry = tmp.geom from ( select s.id,ST_TRANSFORM(ST_LineMerge(t.geom),25832) as geom from elaboration.bluetoothlinks_tmp t join intimev2.station s on t.id=s.id) as tmp where tmp.id=e.edge_data_id;"
        psql -h prod-pg-bdp.co90ybcr8iim.eu-west-1.rds.amazonaws.com -U bdp -d bdp -c "drop table elaboration.bluetoothlinks_tmp;"
